# Theme
remote_theme: pmarsceill/just-the-docs

# Site settings
title: "SQLite3 Multiple&nbsp;Ciphers"
description: SQLite3 encryption extension with support for multiple ciphers
tagline: SQLite3 encryption extension with support for multiple ciphers

#baseurl: "/SQLite3MultipleCiphers"
#url: "https://utelle.github.io"

permalink: pretty
#exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/images/SQLite3MultipleCiphersLogo-420x230.png"

# Enable or disable the site search
search_enabled: true

# Set the search token separator for hyphenated-word search:
search_tokenizer_separator: /[\s/]+/

# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "SQLite3 Multiple Ciphers on GitHub":
    - "//github.com/utelle/SQLite3MultipleCiphers"

# Footer content appears at the bottom of every page's main content
footer_content: "Copyright &copy; 2020 Ulrich Telle. Distributed under an <a href=\"https://github.com/utelle/SQLite3MultipleCiphers/tree/master/LICENSE\">MIT license.</a>"

# Color scheme currently only supports "dark" or nil (default)
color_scheme: nil

plugins:
  - jekyll-seo-tag

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
